/* DO NOT EDIT THIS FILE - it is machine generated */
#ifndef CODES_LAIVY_SERIALIZABLE_ALLOCATOR_H
#define CODES_LAIVY_SERIALIZABLE_ALLOCATOR_H
#include <jni.h>
/* Header for class codes_laivy_serializable_Allocator */

#ifndef _Included_codes_laivy_serializable_Allocator
#define _Included_codes_laivy_serializable_Allocator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     codes_laivy_serializable_Allocator
 * Method:    allocate
 * Signature: (Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_codes_laivy_serializable_Allocator_allocate
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
#endif // CODES_LAIVY_SERIALIZABLE_ALLOCATOR_H
