name: Maven Test

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [8, 9, 12, 17, 20, 21]

    name: Java ${{ matrix.java }} on ${{ matrix.os }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu

      - name: Compile and test with Maven
        run: mvn clean verify

      - name: Display logs
        if: failure()
        run: cat target/surefire-reports/*.txt || type target\surefire-reports\*.txt || true
#  macos:
#    runs-on: ${{ matrix.os }}
#
#    strategy:
#      matrix:
#        os: [macos-latest, macos-13, macos-12]
#        java: [8, 9, 13, 17, 20, 21]
#
#    name: Java ${{ matrix.java }} on ${{ matrix.os }}
#
#    steps:
#      - name: Check out the code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK ${{ matrix.java }}
#        uses: actions/setup-java@v3
#        with:
#          java-version: ${{ matrix.java }}
#          distribution: zulu
#
#      - name: Compile and test with Maven
#        run: mvn clean verify
#
#      - name: Display logs
#        if: failure()
#        run: cat target/surefire-reports/*.txt || type target\surefire-reports\*.txt || true